# Site settings
name: NB eDNA
email:
author: Prada Lab

keywords: eDNA
description: Repository and Site for the Prada Lab's eDNA Project

# Only use this if you are serving your site via Github Pages
github:
  url: "https://meschedl.github.io/eDNA"

header: yes
header_sm: images/IMG_1982.jpeg
header_med: images/IMG_1982.jpeg
header_large: images/IMG_1982.jpeg
header_xl: images/IMG_1982.jpeg


# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

gems:
  - jekyll-feed

feed:
  path: atom.xml

# Compress our Css
#sass:
#    style: :compressed

permalink: /blog/:year/:title

#### SEO Stuff
# Google Analytics
google_universal_analytics:
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                      #enter your App ID
facebook_locale: en_US
facebook_page:                        #the URL of your Facebook Page
facebook_image:                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_user:
twitter_card: false
twitter_image:                        #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
